name: Release

on:
  push:
    branches: 
      - main

permissions:
  contents: write
  pull-requests: write
  
jobs: 
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      paths_released: ${{ steps.release.outputs.paths_released }}
      release_outputs: ${{ toJSON(steps.release.outputs) }}

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
        
      - name: Output release info
        run: |
          echo '${{ toJSON(steps.release.outputs) }}'
        
  release:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.releases_created == 'true' }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Commit dist
        env:
          PAT: ${{ secrets.CI_PUSH_TOKEN }}
        run: |
          echo "Configuring Git..."
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"

          echo "Checkout release-dist branch..."
          git fetch origin
          if git show-ref --verify --quiet refs/heads/release-dist; then
            git checkout release-dist
            git reset --hard origin/release-dist
          else
            git checkout -b release-dist
          fi

          echo "Add and commit dist files..."
          git add -f packages/*/dist
          git commit -m "chore: update dist files [skip ci]" || echo "No changes to commit"
          git push https://$PAT@github.com/${{ github.repository }} release-dist --force

      # Only upload artifacts if releases were created  
      - name: Upload Release Artifact
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PATHS_RELEASED: ${{ needs.release-please.outputs.paths_released }}
          RELEASE_OUTPUTS: ${{ needs.release-please.outputs.release_outputs }}
        run: |
          echo "paths_released = $PATHS_RELEASED"
          for path in $(echo "$PATHS_RELEASED" | jq -r '.[]'); do
            echo "Processing package: $path"
            TAG_NAME=$(echo "$RELEASE_OUTPUTS" | jq -r --arg p "$path" '.[$p + "--tag_name"]')
            echo "Tag for $path = $TAG_NAME"
            gh release upload "$TAG_NAME" "$path/dist/*.js" --clobber || echo "No dist files for $path"
          done
      
